## Numpy Assignment

Ques1:  Compare element of numpy array.

Return True; if all elements are same.

Return False; if all elements are not same.

first_array = np.array([[1, 2], [3, 4]])

second_array = np.array([[1, 2], [3, 4]])

In [1]:
import numpy as np
def compare(first_array,second_array):
    equal=first_array==second_array
    return equal.all()
first_array=np.array([[1,2],[3,4]])
second_array=np.array([[1,2],[3,4]])
compare(first_array,second_array)

True

Ques2: Add a border around a NumPy array, as shown in the figure


[[1,1,1],

[1,1,1],

[1,1,1]]

Output =

[[0,0,0,0,0],

[0,1,1,1,0],

[0,1,1,1,0],

[0,1,1,1,0],

[0,0,0,0,0]]

        

In [2]:
array =np.ones((3,3))
print(array)
array2=np.pad(array,pad_width=1,mode='constant',constant_values=0)
print(array2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Ques3: Calculate the sum of the diagonal elements of a NumPy array

n_array = np.array([[55, 25, 15],

 [30, 44, 2],
 
 [11, 45, 77]])

In [3]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diagonal_sum=np.trace(n_array)
diagonal_sum

176

Ques4: Get the n-largest values of an array using NumPy
Given array: [2 0 1 5 4 1 9]
Find first 3 largest values

In [4]:
array=np.array([2,0,1, 5,4,1 ,9])
print(array)
sort_array=np.sort(array)

print("Three largest values are",sort_array[-3:])

[2 0 1 5 4 1 9]
Three largest values are [4 5 9]


Ques5: Create a 5X2 integer array from a range between 100 to 200 such that
the difference between each element is 10
Your O/p should be:
    
[[100 110]

 [120 130]

 [140 150]

 [160 170]

 [180 190]]

In [5]:
array=np.linspace(100,190,10,dtype=int)
array=array.reshape((5,2))
print(array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Ques6: Following is the given numpy array return array of odd rows and even
columns

Input Array:
    
[[ 3 6 9 12]

 [15 18 21 24]

 [27 30 33 36]

 [39 42 45 48]

 [51 54 57 60]]

Output array:

[[ 6 12]

[30 36]

[54 60]]

In [6]:
array=np.array([[ 3 ,6 ,9 ,12],[15, 18, 21, 24], [27, 30, 33, 36], [39, 42, 45, 48], [51, 54, 57, 60]])
print(array)
sub_array=array[::2,1::2]
print(sub_array)

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


Ques 7: Following is the 2-D array. Print max from axis 0 and min from axis 1
Original array

[[34 43 73]

[82 22 12]

[53 94 66]]

O/P

Minimum of Axis 1: [34 12 53]

Maximum of Axis 0: [82 94 73]

In [7]:
array=np.array([[34,43,73],[82,22,12],[53,94,66]])
min_axis1=np.amin(array,1)
max_axis0=np.amax(array,0)
print("Minimum of Axis 1",min_axis1)
print("Maximum of Axis 0",max_axis0)

Minimum of Axis 1 [34 12 53]
Maximum of Axis 0 [82 94 73]


Ques8: Following is the input NumPy array delete column two and insert
following new column in its place.

Original Array

[[34 43 73]

[82 22 12]

[53 94 66]]

Required O/P

[[34 10 73]

[82 10 12]

[53 10 66]]

In [8]:
array=np.array([[34,43,73],[82,22,12],[53,94,66]])
array=np.delete(array,1,axis=1)
new_column=np.array([10,10,10])
array=np.insert(array,1,new_column,axis=1)
print(array)

[[34 10 73]
 [82 10 12]
 [53 10 66]]


Ques9: Remove those elements from one array that exist in another array?
(without loop)
Input

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

Output

array([1,2,3,4])

In [9]:
a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])
s=dict()
for i in range(len(b)):
    s[b[i]]=1
for i in range(len(a)):
    if a[i] not in s.keys():
        print(a[i],end=" ")


1 2 3 4 

In [10]:
## Another method
set_d=np.setdiff1d(a,b)
print(set_d)

[1 2 3 4]


Ques10: Normalize the values of the numpy array (i.e it means each element
should be between 0 & 1)?

In [11]:
array=np.array([34,56,2,8,9,67,4,5,45,67,89])
minn,maxx=array.min(),array.max()
normalise=(array-minn)/(maxx-minn)
print(normalise)
#print(maxx,minn)

[0.36781609 0.62068966 0.         0.06896552 0.08045977 0.74712644
 0.02298851 0.03448276 0.49425287 0.74712644 1.        ]


Ques11: Replace all the missing values of the numpy array with 0?
arr = np.array([[125, np.NaN, 514, np.NaN, np.NaN, 12],
 [np.NaN, 13, 45, 59, 28, np.NaN]])

In [12]:
arr = np.array([[125, np.NaN, 514, np.NaN, np.NaN, 12],[np.NaN, 13, 45, 59, 28, np.NaN]])
print(np.nan_to_num(arr))

[[125.   0. 514.   0.   0.  12.]
 [  0.  13.  45.  59.  28.   0.]]


Ques12: Convert an Array of arrays to flat 1D array? (with loop and without loop)
Input:
arr = [[0 1 2]
[3 4 5]
[6 7 8]]
Output: array([0,1,2,3,4,5,6,7,8,9])

In [13]:
arr = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
print(arr.flatten())

[0 1 2 3 4 5 6 7 8]


In [14]:
arr = np.array([[0, 1, 2],[3, 4, 5],[6, 7, 8]])
arr1=[]
for i in arr:
    for j in i:
        arr1.append(j)
print(arr1)

[0, 1, 2, 3, 4, 5, 6, 7, 8]


Ques13: Convert any Image to Numpy Array and Vice versa?

In [15]:
from PIL import Image
from numpy import asarray
img=Image.open("GndecLogo.png")
print(img.size,img.mode,img.format)
np_data=asarray(img)
print(type(np_data))
print(np_data.shape)
print(np_data)

(440, 394) RGBA PNG
<class 'numpy.ndarray'>
(394, 440, 4)
[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 ...

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]


Ques14: Compute Euclidean Distance b/w 2 arrays? (without using inbuilt
function i.e. do not use np.linalg.norm)

In [16]:
point1=np.array([4,2,3])
point2=np.array([2,1,1])
sum_sq = np.sum(np.square(point1 - point2))
print(np.sqrt(sum_sq))


3.0
